services:
    tms_model_io.handler.import_export:
        class: Tms\Bundle\ModelIOBundle\Handler\ImportExportHandler
        arguments: [@tms_model_io.handler.file, @tms_model_io.serializer.import_export, null]
        abstract: true

    tms_model_io.handler.file:
        class: Tms\Bundle\ModelIOBundle\Handler\FileHandler
        arguments: [%import_directory%]

    tms_model_io.serializer.import_export:
        class: Tms\Bundle\ModelIOBundle\Serializer\ImportExportSerializer
        arguments: []

    tms_model_io.form.type.import:
        class: Tms\Bundle\ModelIOBundle\Form\Type\ImportType
        tags:
            - { name: form.type, alias: tms_model_io.import }
