services:
    tms_model_io.handler.import_export:
        class: Tms\Bundle\ModelIOBundle\Handler\ImportExport
        arguments: [@tms_model_io.serializer.import_export_serializer]

    tms_model_io.handler.import_export_handler:
        class: Tms\Bundle\ModelIOBundle\Handler\ImportExportHandler
        arguments: [null, null, null, null, @tms_model_io.handler.import_export]
        abstract: true
        public: false

    tms_model_io.serializer.import_export_serializer:
        class: Tms\Bundle\ModelIOBundle\Serializer\ImportExportSerializer
        arguments: []
