services:
    tms_model_io.handler.file_handler:
        class: Tms\Bundle\ModelIOBundle\Handler\FileHandler
        arguments:
            - '%import_directory%'

    tms_model_io.handler.media_handler:
        class: Tms\Bundle\ModelIOBundle\Handler\MediaHandler
        arguments:
            - '@tms_media_client.storage_provider.tms_media'

    tms_model_io.form.type.import:
        class: Tms\Bundle\ModelIOBundle\Form\Type\ImportType
        tags:
            - { name: form.type, alias: tms_model_io_import }

    tms_model_io.manager.import_export_manager:
        class: Tms\Bundle\ModelIOBundle\Manager\ImportExportManager
        arguments:
            - '@tms_model_io.serializer.import_export_serializer'

    tms_model_io.handler.import_export_handler:
        class: Tms\Bundle\ModelIOBundle\Handler\ImportExportHandler
        arguments:
            - null
            - null
            - null
            - null
            - null
            - null
            - '@tms_model_io.manager.import_export_manager'
            - '@?tms_model_io.handler.media_handler'
        abstract: true
        public: false

    tms_model_io.serializer.import_export_serializer:
        class: Tms\Bundle\ModelIOBundle\Serializer\ImportExportSerializer
        arguments: []

    tms_model_io.importer.entity:
        class: Tms\Bundle\ModelIOBundle\Import\EntityImporter
        arguments:
            - '@jms_serializer'
            - '@doctrine.orm.entity_manager'
